# -*- coding: utf-8 -*-
"""streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AyK_CQTXxM4FROfRCX8nyaORQZeU1Kba
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import io

st.set_page_config(page_title="Análisis y Evaluación de Avisos", layout="wide")
st.title("Aplicación de Análisis y Evaluación")

# --- Subida del archivo ---
st.sidebar.header("1. Subir archivo Excel")
file = st.sidebar.file_uploader("Selecciona tu archivo .xlsx", type=["xlsx"])

if file:
    @st.cache_data
    def load_and_merge_data(uploaded_file):
        xls = pd.ExcelFile(uploaded_file)
        iw29 = pd.read_excel(xls, sheet_name=0)
        iw39 = pd.read_excel(xls, sheet_name=1)
        ih08 = pd.read_excel(xls, sheet_name=2)
        iw65 = pd.read_excel(xls, sheet_name=3)
        zpm015 = pd.read_excel(xls, sheet_name=4)

        for df in (iw29, iw39, ih08, iw65, zpm015):
            df.columns = df.columns.str.strip()

        equipo_original = iw29[["Aviso", "Equipo", "Duración de parada", "Descripción"]].copy()
        iw39_subset = iw39[["Aviso", "Total general (real)"]]

        tmp1 = pd.merge(iw29, iw39_subset, on="Aviso", how="left")
        tmp2 = pd.merge(tmp1, iw65, on="Aviso", how="left")
        tmp2.drop(columns=["Equipo"], errors='ignore', inplace=True)
        tmp2 = pd.merge(tmp2, equipo_original, on="Aviso", how="left")
        tmp3 = pd.merge(tmp2, ih08[["Equipo", "Denominación"]], on="Equipo", how="left")
        df_final = pd.merge(tmp3, zpm015, on="Aviso", how="left")

        return df_final

    df = load_and_merge_data(file)
    st.success("Archivo procesado correctamente. ✅")

    # --- Filtros ---
    st.sidebar.header("2. Filtros")
    proveedor_opciones = df["Proveedor"].dropna().unique() if "Proveedor" in df.columns else []
    equipo_opciones = df["Equipo"].dropna().unique() if "Equipo" in df.columns else []

    proveedor = st.sidebar.multiselect("Filtrar por Proveedor", proveedor_opciones)
    equipo = st.sidebar.multiselect("Filtrar por Equipo", equipo_opciones)

    df_filtrado = df.copy()
    if proveedor:
        df_filtrado = df_filtrado[df_filtrado["Proveedor"].isin(proveedor)]
    if equipo:
        df_filtrado = df_filtrado[df_filtrado["Equipo"].isin(equipo)]

    # --- Menú de navegación ---
    opcion = st.sidebar.radio("3. Selecciona una opción:", ["Análisis", "Evaluación"])

    # --- ANÁLISIS ---
    if opcion == "Análisis":
        st.header("🔍 Análisis de Costos y Equipos")

        if "Ejecutante" in df_filtrado.columns and "Total general (real)" in df_filtrado.columns:
            costos_por_ejecutante = df_filtrado.groupby("Ejecutante")["Total general (real)"].sum().sort_values()
            fig, ax = plt.subplots(figsize=(10, 5))
            sns.barplot(x=costos_por_ejecutante.values, y=costos_por_ejecutante.index, palette="Blues_r", ax=ax)
            ax.set_xlabel("Costo Total ($)")
            ax.set_ylabel("Ejecutante")
            ax.set_title("Costo Total por Ejecutante")
            st.pyplot(fig)
        else:
            st.warning("No se encontró la columna 'Ejecutante' o 'Total general (real)'.")

        st.dataframe(df_filtrado.head(20))

    # --- EVALUACIÓN ---
    elif opcion == "Evaluación":
        st.header("✅ Evaluación Cualitativa")

        aviso_seleccionado = st.selectbox("Selecciona un aviso para evaluar", df_filtrado["Aviso"].unique())
        aviso_data = df_filtrado[df_filtrado["Aviso"] == aviso_seleccionado].iloc[0]

        st.write("### Detalles del aviso")
        st.write({
            "Equipo": aviso_data.get("Equipo"),
            "Descripción": aviso_data.get("Descripción"),
            "Duración de parada": aviso_data.get("Duración de parada"),
            "Total general (real)": aviso_data.get("Total general (real)")
        })

        with st.expander("🔎 Mostrar rangos detallados de evaluación"):
            st.markdown("""
            **Escala General:**
            - **2:** Sobresaliente
            - **1:** Bueno
            - **0:** Indiferente
            - **-1:** Malo

            *(Los rangos específicos por pregunta están integrados en la lógica interna de evaluación.)*
            """)

        st.write("### Evaluación cualitativa con preguntas")

        pregunta_1 = st.slider("¿Las soluciones propuestas son coherentes con el diagnóstico y causa raíz del problema?", -1, 2, 0)
        pregunta_2 = st.slider("¿El trabajo entregado tiene materiales nuevos, originales y de marcas reconocidas?", -1, 2, 0)
        pregunta_3 = st.slider("¿Cuenta con acabados homogéneos, limpios y pulidos?", -1, 2, 0)
        pregunta_4 = st.slider("¿El trabajo entregado corresponde completamente con lo contratado?", -1, 2, 0)
        pregunta_5 = st.slider("¿La facturación refleja correctamente lo ejecutado y acordado?", -1, 2, 0)

        promedio = np.mean([pregunta_1, pregunta_2, pregunta_3, pregunta_4, pregunta_5])
        st.success(f"Puntaje promedio: {promedio:.2f} / 2")

        # --- Mostrar resultados en tabla ---
        evaluacion_df = pd.DataFrame({
            "Aviso": [aviso_seleccionado],
            "P1_Coherencia": [pregunta_1],
            "P2_Materiales": [pregunta_2],
            "P3_Acabados": [pregunta_3],
            "P4_Cumplimiento": [pregunta_4],
            "P5_Facturación": [pregunta_5],
            "Promedio": [promedio]
        })

        st.write("### Resultado de evaluación")
        st.dataframe(evaluacion_df)

    # --- Descarga de archivo procesado ---
    output = io.BytesIO()
    df_filtrado.to_excel(output, index=False, engine='xlsxwriter')
    st.sidebar.download_button(
        label="📥 Descargar Excel filtrado",
        data=output.getvalue(),
        file_name="avisos_filtrados.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

else:
    st.info("Por favor sube un archivo Excel para comenzar.")